Adding executionStartedTimestamp property to ExecutionStartedEvent message
microsoft/durabletask-protobuf pull request #22
Opened 2024-01-17 13:35 UTC by ASHIQUEMD

This PR adds executionStartedTimestamp property to ExecutionStartedEvent, to capture the execution started timestamp for workflow.

2024-01-17 16:49 UTC, cgillum requested changes
We should not be adding this property here. An indication of when execution started should instead be done on `OrchestrationState`.

2024-01-18 12:11 UTC, ASHIQUEMD commented
> We should not be adding this property here. An indication of when execution started should instead be done on `OrchestrationState`.

Hello @cgillum, thank you for your suggestion. I wanted to clarify that we don't directly persist OrchestrationState; it is derived from HistoryEvent. If I understand correctly, you're proposing adding executionStartedTimestamp to OrchestrationState. If that's the case, the challenge lies in persisting this information, as I couldn't find an exposed API in dtf-go to save the OrchestrationState directly. The available API, FetchOrchestrationMetadata, retrieves the state from HistoryEvent. Please correct me if my understanding is not accurate or if there's a different approach you have in mind.

2024-01-19 09:28 UTC, DeepanshuA commented
Yeah, `OrchestrationState` is not persisted directly. It is created through workflowState saved by backend. And, this workflowState is being saved in terms of `HistoryEvents`. 
So, I also understand the same thing that we would need to persist in `ExecutionStartedEvent` and that should be the correct place for it.

2024-01-19 19:29 UTC, cgillum commented
You don't need a new property for this. You can use the timestamp on the very first `HistoryEvent` of type `OrchestratorStarted` in the history, which gets added only after the orchestration starts executing.

2024-01-25 09:00 UTC, ASHIQUEMD commented
Closing this PR as it is no longer required.

2024-01-25 09:00 UTC, closed without merging